In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
print(a.dtype)
print(a)


int32
[1 2 3 4]


In [7]:
a = np.array(12)
print(a.ndim)
print(a)

0
12


In [10]:
a = np.array([1,2,3,4])
print(a.dtype)
print(a.ndim)   # Specifies the dimension
print(a.shape)  #It gives the length
print(a)


int32
1
(4,)
[1 2 3 4]


In [11]:
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a.dtype)
print(a.ndim)   # Specifies the dimension
print(a.shape)  #It gives the length
print(a)

int32
2
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
a =np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(a.dtype)
print(a.ndim)   # Specifies the dimension
print(a.shape)  #It gives the length
print(a)

int32
3
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
a =np.array([[[1,2,3,4]], [[5,6,7,8]]])
print(a.dtype)
print(a.ndim)   # Specifies the dimension
print(a.shape)  #It gives the length
print(a)

int32
3
(2, 1, 4)
[[[1 2 3 4]]

 [[5 6 7 8]]]
